### ISSUE TITLE
docs: Update Readme

### ISSUE THREAD

**Issue by kunalkumar007** [RajvirSingh1313/Elecrue#8]
I get to know that the ReadME update is in a pending state. So, I would like to be working on it.

**Comment by RajvirSingh1313** [comment]
@kunalkumar007 Yeah Sure, But before that, I need to do some changes. So when I will be done, I will inform you

**Comment by kunalkumar007** [comment]
- As Of now, there is some work to be done before the README. 
- Hence, I am closing the issue.
- Open a new issue when you are ready. 😄
