### ISSUE TITLE
Adding LICENSE section in README.md 

### ISSUE THREAD

**Issue by Pradumnasaraf** [RajvirSingh1313/Elecrue#9]
Adding LICENSE section in README.md @RajvirSingh1313

**Comment by RajvirSingh1313** [comment]
Ah @Pradumnasaraf , Can you explain a bit further

**Comment by Pradumnasaraf** [comment]
I mean adding a section in the README.md file to show details about the repo licensing. I think every **licensed repo** should contain it.
 
**Sample**
![s](https://user-images.githubusercontent.com/51878265/135704104-344e85e4-4298-4731-ac20-39a7c6fa191d.png)

@RajvirSingh1313

**Comment by RajvirSingh1313** [comment]
@Pradumnasaraf Thanks I have added it now. Thanks for taking your time, informing me
